name = "k-client-streams"
main = "src/index.ts"
compatibility_date = "2025-04-30"

compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[migrations]]
tag = "v1"
new_classes = ["StreamConsumer"]




[[durable_objects.bindings]]
name = "STREAMCONSUMER"
class_name = "StreamConsumer"
[vars]
UPSTASH_REDIS_URL = 'https://learning-caribou-32038.upstash.io'
UPSTASH_REDIS_TOKEN = 'AX0mAAIjcDE1NmViMzk1M2Y3YTg0YTE0OTc2MWNjODA2MmRlNjIyNXAxMA'
UPSTASH_REDIS_STREAM_NAME = 'k-stream'
NATS_CRED_JWT = "eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJZVzNMQ0E0N0NIUEozTkVCUjdRWk9HUFJDQlNDRTZYTktYTlUzREtBM1RVNk5JQ0dXTlZRIiwiaWF0IjoxNzQ2MTcxMTczLCJpc3MiOiJBQUJVUFBNRk5JVFZWWVFXQVJVWUhWTTVHTlRYRTNXRVNQVlZOT1VJN01DV0ZZSUhORjJLSDVENSIsIm5hbWUiOiJrLXN0cmVhbS11c2VyIiwic3ViIjoiVUNHNlRETVQ2M1NBUkxBN1BSNVQzVE1WRVlKN0NSWkI2WjNEN1pSWkdJUzNOQU1MSk9SSVdNVkQiLCJuYXRzIjp7InB1YiI6eyJhbGxvdyI6WyIqIl19LCJzdWIiOnsiYWxsb3ciOlsiKiJdfSwic3VicyI6LTEsImRhdGEiOi0xLCJwYXlsb2FkIjotMSwiaXNzdWVyX2FjY291bnQiOiJBQUtTU0VTSzVBV0ZUWURaUUJTQVlaWVdLNFNGQkxSS0hDUEM0Q0dHWlREU1dWRE5NSjdQTTRSQiIsInR5cGUiOiJ1c2VyIiwidmVyc2lvbiI6Mn19.X3y10qfMEUO5TjwyqBNVfwM5rZKWSKMzYQcWbgDY2LHsxHpVD8EJPxDKu-ikp2UpBmT1nECbH8U_PDILEHTWCw"


NATS_CRED_KEY_SEED="SUAK6CT7SARDHB54G6MXOEZBR4KIG72WPNPM5KPHA6UWKBKP5KG6WECMII"
